const applicationsData = [
  {
    id: 1, name: 'Alex Rivera', initials: 'AR',
    role: 'Senior Frontend Developer', company: 'TechHive',
    status: 'Shortlisted', date: '2 hours ago',
    email: 'alex.rivera@email.com', phone: '+1 (555) 234-5678',
    linkedin: 'linkedin.com/in/alexrivera', location: 'San Francisco, CA',
    experience: '5 years', appliedRole: 'Senior Frontend Developer',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'CSS'],
    summary: 'Experienced frontend engineer with a strong focus on React and TypeScript. Led the frontend rewrite at TechHive resulting in a 40% improvement in load times.',
    history: [
      { stage: 'Applied',     date: 'May 1, 2026' },
      { stage: 'Reviewed',    date: 'May 2, 2026' },
      { stage: 'Shortlisted', date: 'May 2, 2026' },
    ],
  },
  {
    id: 2, name: 'Priya Sharma', initials: 'PS',
    role: 'UX/UI Designer', company: 'DesignBuzz',
    status: 'Reviewing', date: '5 hours ago',
    email: 'priya.sharma@email.com', phone: '+1 (555) 876-4321',
    linkedin: 'linkedin.com/in/priyasharma', location: 'Remote',
    experience: '4 years', appliedRole: 'UX/UI Designer',
    skills: ['Figma', 'Prototyping', 'User Research', 'Sketch', 'Design Systems'],
    summary: 'Creative UX designer passionate about building intuitive, accessible products. Designed the flagship app at DesignBuzz used by 200k+ monthly users.',
    history: [
      { stage: 'Applied',  date: 'May 1, 2026' },
      { stage: 'Reviewed', date: 'May 2, 2026' },
    ],
  },
  {
    id: 3, name: "James O'Brien", initials: 'JO',
    role: 'Backend Engineer', company: 'CloudForge',
    status: 'Reviewing', date: '1 day ago',
    email: 'james.obrien@email.com', phone: '+1 (555) 321-9876',
    linkedin: 'linkedin.com/in/jamesobrien', location: 'New York, NY',
    experience: '6 years', appliedRole: 'Backend Engineer',
    skills: ['Go', 'Python', 'Kubernetes', 'PostgreSQL', 'AWS'],
    summary: 'Backend engineer specializing in distributed systems and cloud infrastructure. Built and scaled microservices handling 10M+ requests/day at CloudForge.',
    history: [
      { stage: 'Applied',  date: 'Apr 30, 2026' },
      { stage: 'Reviewed', date: 'May 1, 2026' },
    ],
  },
  {
    id: 4, name: 'Fatima Al-Zahra', initials: 'FA',
    role: 'Data Scientist', company: 'DataMinds',
    status: 'Shortlisted', date: '1 day ago',
    email: 'fatima.alzahra@email.com', phone: '+1 (555) 654-3210',
    linkedin: 'linkedin.com/in/fatimaalzahra', location: 'Austin, TX',
    experience: '3 years', appliedRole: 'Data Scientist',
    skills: ['Python', 'TensorFlow', 'SQL', 'Tableau', 'R'],
    summary: 'Data scientist with a focus on ML model deployment and analytics. Built a churn prediction model at DataMinds saving $2M in annual revenue.',
    history: [
      { stage: 'Applied',     date: 'Apr 30, 2026' },
      { stage: 'Reviewed',    date: 'May 1, 2026' },
      { stage: 'Shortlisted', date: 'May 1, 2026' },
    ],
  },
  {
    id: 5, name: 'Marcus Chen', initials: 'MC',
    role: 'DevOps Engineer', company: 'InfraCore',
    status: 'Rejected', date: '2 days ago',
    email: 'marcus.chen@email.com', phone: '+1 (555) 111-2222',
    linkedin: 'linkedin.com/in/marcuschen', location: 'Seattle, WA',
    experience: '2 years', appliedRole: 'DevOps Engineer',
    skills: ['Docker', 'Terraform', 'CI/CD', 'Linux', 'Azure'],
    summary: 'Junior DevOps engineer with experience building CI/CD pipelines and container orchestration. Eager to grow in a fast-paced environment.',
    history: [
      { stage: 'Applied',   date: 'Apr 29, 2026' },
      { stage: 'Reviewed',  date: 'Apr 30, 2026' },
      { stage: 'Rejected',  date: 'May 1, 2026'  },
    ],
  },
  {
    id: 6, name: 'Sofia Iannone', initials: 'SI',
    role: 'Digital Marketing Manager', company: 'GrowthNest',
    status: 'Reviewing', date: '2 days ago',
    email: 'sofia.iannone@email.com', phone: '+1 (555) 444-5555',
    linkedin: 'linkedin.com/in/sofiaiannone', location: 'Chicago, IL',
    experience: '7 years', appliedRole: 'Digital Marketing Manager',
    skills: ['SEO', 'Google Ads', 'HubSpot', 'Content Strategy', 'Analytics'],
    summary: 'Results-driven marketer who grew organic traffic by 300% at GrowthNest through strategic SEO and content campaigns.',
    history: [
      { stage: 'Applied',  date: 'Apr 29, 2026' },
      { stage: 'Reviewed', date: 'Apr 30, 2026' },
    ],
  },
  {
    id: 7, name: 'Liam Nguyen', initials: 'LN',
    role: 'Mobile App Developer', company: 'AppAxis',
    status: 'Shortlisted', date: '3 days ago',
    email: 'liam.nguyen@email.com', phone: '+1 (555) 777-8888',
    linkedin: 'linkedin.com/in/liamnguyen', location: 'Remote',
    experience: '4 years', appliedRole: 'Mobile App Developer',
    skills: ['React Native', 'Swift', 'Kotlin', 'Firebase', 'Redux'],
    summary: 'Full-stack mobile developer with apps live in both the App Store and Google Play with a combined 500k+ downloads.',
    history: [
      { stage: 'Applied',     date: 'Apr 28, 2026' },
      { stage: 'Reviewed',    date: 'Apr 29, 2026' },
      { stage: 'Shortlisted', date: 'Apr 30, 2026' },
    ],
  },
  {
    id: 8, name: 'Hannah Brooks', initials: 'HB',
    role: 'Financial Analyst', company: 'CapitalWing',
    status: 'Rejected', date: '3 days ago',
    email: 'hannah.brooks@email.com', phone: '+1 (555) 999-0000',
    linkedin: 'linkedin.com/in/hannahbrooks', location: 'Boston, MA',
    experience: '3 years', appliedRole: 'Financial Analyst',
    skills: ['Excel', 'Power BI', 'Financial Modeling', 'SQL', 'Bloomberg'],
    summary: 'Financial analyst with experience in equity research and portfolio modeling. Built automated reporting tools reducing monthly close time by 30%.',
    history: [
      { stage: 'Applied',  date: 'Apr 28, 2026' },
      { stage: 'Reviewed', date: 'Apr 29, 2026' },
      { stage: 'Rejected', date: 'Apr 30, 2026' },
    ],
  },
];

export default applicationsData;
